/* eslint-disable @next/next/no-img-element */

import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — CueAside",
  description:
    "The terms that apply to your CueAside account, subscription, and use of the app during early access.",
  alternates: {
    canonical: "/terms/",
  },
};

export default function TermsOfService() {
  return (
    <main className="legal-page">
      <header className="masthead">
        <div className="masthead-inner">
          <Link className="masthead-brand" href="/" aria-label="CueAside home">
            <img src="/cueaside-icon.png" alt="" width={28} height={28} />
            CueAside
          </Link>
          <Link className="mono" href="/">
            ← Back to the document
          </Link>
        </div>
      </header>

      <article className="legal-body">
        <div className="mono" style={{ color: "var(--stamp)" }}>
          Terms of Service
        </div>
        <h1>Plain terms for an early-access product.</h1>
        <p className="legal-updated">Last updated: July 30, 2026</p>

        <section>
          <h2>What CueAside is</h2>
          <p>
            CueAside is a macOS app and hosted API that provide live,
            AI-generated speaking guidance during interviews, meetings, and
            other professional conversations. By creating an account or using
            the app, you agree to these terms.
          </p>
        </section>

        <section>
          <h2>Early access</h2>
          <p>
            CueAside is in active development. Features may change, break, or
            be removed while we improve the product. We will communicate
            significant changes, but early-access software comes with rough
            edges—please expect some.
          </p>
        </section>

        <section>
          <h2>Your account</h2>
          <p>
            You need a valid email address to sign in. You are responsible for
            activity under your account and for keeping access to your email
            secure. One account is for one person; shared accounts are not
            allowed.
          </p>
        </section>

        <section>
          <h2>Subscriptions and billing</h2>
          <ul>
            <li>
              Paid plans are billed through Stripe and renew automatically
              until canceled.
            </li>
            <li>
              You can cancel anytime from the billing portal; access continues
              through the end of the paid period.
            </li>
            <li>
              Fair-use limits apply to AI requests each day so the service
              stays fast and affordable for everyone.
            </li>
          </ul>
        </section>

        <section>
          <h2>Using CueAside responsibly</h2>
          <p>
            CueAside helps you use your own preparation in real time. It does
            not remove your obligations to other people or organizations. You
            are responsible for:
          </p>
          <ul>
            <li>
              complying with rules that apply to your conversations, including
              an employer’s, school’s, or interviewer’s policies on assistance;
            </li>
            <li>
              complying with recording and consent laws in your region and the
              regions of other participants;
            </li>
            <li>the accuracy of what you ultimately say and represent.</li>
          </ul>
          <p>
            You may not use CueAside to break the law, to harass others, to
            attempt to extract our API keys or circumvent usage limits, or to
            resell access to the hosted API.
          </p>
        </section>

        <section>
          <h2>AI output</h2>
          <p>
            Answers are generated by AI from your context and the live
            conversation. They can be wrong, incomplete, or inappropriate for
            your situation. Treat them as a prompt for your own judgment, not a
            guarantee.
          </p>
        </section>

        <section>
          <h2>Ownership</h2>
          <p>
            The CueAside app, API, brand, and website are ours. The context you
            provide and the things you say remain yours. We claim no rights to
            your conversations.
          </p>
        </section>

        <section>
          <h2>Warranty and liability</h2>
          <p>
            CueAside is provided “as is” without warranties of any kind. To the
            extent permitted by law, our total liability for any claim related
            to the service is limited to the amount you paid us in the twelve
            months before the claim.
          </p>
        </section>

        <section>
          <h2>Cancellation and refunds</h2>
          <p>
            Subscriptions renew monthly until canceled. Cancel any time from
            the Stripe billing portal inside the app — no email, no phone
            call. Cancellation takes effect at the end of the paid period, and
            you keep access until then. If a charge was a mistake — a double
            charge, a renewal right after you canceled — write to{" "}
            <a href="mailto:support@cueaside.com">support@cueaside.com</a> and
            we will put it right.
          </p>
        </section>

        <section>
          <h2>System requirements</h2>
          <p>
            CueAside is a native macOS app and requires macOS 15.3 or later.
            It does not run on Windows, and there is no web version of the
            overlay.
          </p>
        </section>

        <section>
          <h2>Ending service</h2>
          <p>
            You can stop using CueAside and delete your account at any time. We
            may suspend or terminate accounts that violate these terms or
            threaten the service’s integrity, with a refund of any unused paid
            period when the termination is not for abuse.
          </p>
        </section>

        <section>
          <h2>Changes and contact</h2>
          <p>
            We may update these terms as the product evolves; the date above
            reflects the latest revision. Questions go to{" "}
            <a href="mailto:support@cueaside.com">support@cueaside.com</a>.
          </p>
        </section>
      </article>

      <footer className="doc-footer">
        <span>© 2026 CueAside · macOS</span>
        <nav>
          <Link href="/">Home</Link>
          <a href="/privacy/">Privacy</a>
          <a href="/terms/">Terms</a>
        </nav>
      </footer>
    </main>
  );
}
